version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Trolli!
      MYSQL_DATABASE: ONEHADA_localDB
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
