name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          # Backend build and push
          cd backend
          echo "Building backend..."
          docker build -t $DOCKER_USERNAME/backend:latest .
          docker push $DOCKER_USERNAME/backend:latest
          
          # Frontend build and push
          cd ../frontend
          echo "Building frontend..."
          docker build -t $DOCKER_USERNAME/frontend:latest .
          docker push $DOCKER_USERNAME/frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app
            
            # Create .env file with all necessary variables
            cat << EOF > .env
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            EOF
            
            # Set proper permissions
            chmod 600 .env
            
            # Deploy
            docker-compose pull
            docker-compose down
            docker-compose up -d
